name: Deploy Kaizen Assignment to Vercel

on:
  push:
    branches:
      - main   # For production deployment
      - development  # For staging deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel (Staging or Production)
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          else
            npx vercel --token ${{ secrets.VERCEL_TOKEN }}


      # Optionally, you can add a test step to ensure everything is correct before deploying
      # - name: Run tests
      #   run: npm test
