name: Deploy React TypeScript App to Vercel

on:
  push:
    branches:
      - main   # For production deployment
      - development  # For staging deployment

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.0.0'
      
      - name: Clear cache and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
    
      # - name: Start Vite server
      #   run: npm run dev &
      #   env:
      #     CI: true
  
      # - name: Wait for server to start
      #   run: |
      #     while ! nc -z localhost 5173; do
      #       sleep 1
      #     done
      #   env:
      #     CI: true

      # - name: Run unit tests (Jest)
      #   run: npm run test

      # - name: Run Cypress E2E tests
      #   run: npx cypress run --headless

  deploy:
    runs-on: ubuntu-latest
    needs: test
    # if: success() # Only deploy if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '^18.18.0'

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel (Staging or Production)
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          else
            npx vercel --token ${{ secrets.VERCEL_TOKEN }}
          fi
